name: Build Site Index

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          
      - name: Install dependencies
        run: go mod download

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Format code
        run: make fmt
        
      - name: Build project
        run: make build
        
      - name: Execute project
        run: make exec
        
      - name: Commit changes
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          git commit -m "Auto-commit changes after build" || echo "No changes to commit"
          git push origin main

      - name: Build site
        run: make build-site
